# Generated by Django 3.0.7 on 2020-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200724_1612'),
    ]

    operations = [
        migrations.DeleteModel(
            name='verification_code',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
